### ISSUE TITLE
Greetings & guidance with running drone indoors

### ISSUE THREAD

**Issue by sanjivvenkatram1972** [dronekit/dronekit-python#1211]
Greetings,

Hope all well. Thanks in advance for guidance and I am planning on running my pixhawk 2.4.8 drone indoors (ONLY). Would it be possible for me to use overrides and control the drone from Python? As I will not have access to GPS, currently I can't pwm the motors as pre-arm checks fail. I am a bit unsure of disabling GPS and concerned about the impact it might have on stability.

Much appreciate the kind assistance.

Kind regards,

Sanjiv

**Comment by hamishwillee** [comment]
You are best off asking this in the gitter channel. 

It is impossible to answer this in any case, because it depends on what flight stack you are using.  pixhawk 2.4.8 is (very very very out of date legacy) hardware. Whether you can run without GPS depends on what other hardware you have and software. 

In any case it isn't something we would answer as an issue or enhancement request in this area.
