### ISSUE TITLE
Could not pip the simulator

### ISSUE THREAD

**Issue by anandbaskaran** [dronekit/dronekit-python#602]
I am new to Drone kit and I am trying download the simulator by running `pip install dronekit-sitl`. But it says there exists some syntax error in the code. Please find the attached image for the detailed description.
![capture](https://cloud.githubusercontent.com/assets/6847984/13527742/979cbba8-e211-11e5-9671-a7f0e46399be.PNG)

**Comment by peterbarker** [comment]
On Fri, 4 Mar 2016, Anand wrote:

> I am new to Drone kit and I am trying download the simulator by running pip
> install dronekit-sitl. But it says there exists some syntax error in the
> code. Please find the attached image for the detailed description.
> capture

That's a bug!

It has been fixed for several months in the master branch (see f9c84eff) - 
apparently it is past time for a release!

You can avoid this bug by using Python 2 rather than Python 3.

Yours,
-- 
Peter Barker                          |   Programmer,Sysadmin,Geek.
pbarker@barker.dropbear.id.au	      |   You need a bigger hammer.
:: It's a hack! Expect underscores! - Nigel Williams

**Comment by hamishwillee** [comment]
YOu can install from master using:

```
pip install -UI git+https://github.com/dronekit/dronekit-sitl
```

@peterbarker Are you making a new release?

**Comment by anandbaskaran** [comment]
Even when I use Python2 I get a similar kind of error. I tried the command given bu hamishwillee too, but no progress :(

**Comment by anandbaskaran** [comment]
Its working in master with Python 2 :) Thank you :+1:
