### ISSUE TITLE
Setting EXIF fields for lat/long/alt through the gimbal class

### ISSUE THREAD

**Issue by DarylWM** [dronekit/dronekit-python#607]
For stitching images into maps, I need the current lat/long/alt injected into the EXIF header of each image. Is this likely to be a feature of the gimbal class?

**Comment by franknitty69** [comment]
Daryl, exif data would have to be set by the GoPro. dronekit can change modes or take pictures, but it cannot alter the files on the gopro sd card. this is the reason that current method, even with other apm drones, is to write a log with this information and inject the information from the log into the images after downloading from the camera.

for dronekit to be able to set exif, dronekit would have to grab a frame from the current video stream, get the current lat/long/alt and write the image to solo with that exif info. this isn't the best way because the frame grab isn't going to best quality.

**Comment by DarylWM** [comment]
Thanks Ahmed.
