### ISSUE TITLE
parameters to control throttle

### ISSUE THREAD

**Issue by Eulerianial** [dronekit/dronekit-python#744]
What are the parameters to control the throttle.
I want to manually control throttle and define  (x,y,z) to move the drone as opposed to vehicle.simple_takeoff API calls. Any hints?

**Comment by hamishwillee** [comment]
What you want to do can be done with RC overrides - search in docs. You won't find much information because this is something the autopilot people REALLY do NOT want you to do. Best think to do is raise the question on gitter (https://gitter.im/dronekit/dronekit-python) describing the *problem that you are trying to solve* (not the solution that you want). There are people there who have probably faced the problem and will be able to outline the correct options.
