### ISSUE TITLE
Simple way for hovering at constant altitude with Dronekit

### ISSUE THREAD

**Issue by srediske** [dronekit/dronekit-python#962]
Hello again,
i'm working with Arducopter 3.7.0 / SITL (sim_vehicle.py) and Gazebo 9 and try to build a simple hover script. The Drone should takeoff to a specific altitude and hover at that altitude, but i want to control roll and pitch from external input (like rc override).

So far my script takeoff in STABILIZE with `vehicle.channels.override` and switch into ALT_HOLD when reaching the desired altitude. But as soon as the script stop to publish the rc override the drone fall down (which has been explained on the Doc's - i know). 
To make a long story short, with the mavproxy command rc 3 1500 the Drone hover perfectly and i'm looking for a similar way to accomplish this with Dronekit or at least with a direct mavlink command (maybe do_set_servo ?).

**Comment by Tyron1406** [comment]
I might have a solution to work on, but I have no expertise yet to write out the solution. Wind obviously is a problem with drones, and so is taking fine readings from the gyro. My idea in my "ultimate-drone' for this problem is to set up a 'hair'-like tool on the top of the drone which senses wind movement and the direction of the wind. I believe this can be done using piezo crystals that send info to a controller. To add to the solution I would also have a camera pointing downwards that detects objects and/or patterns on the ground and traces their parallax and finely adjusts the flight to try to keep the drone in the same place. This link could be a start on this idea... https://youtu.be/4KiH3Fq3olM

I'm hoping these ideas can help.
